version: '3'

services:
  btc:
    container_name: btc-service
    #command: "yes"
    privileged: true 
    build: ./btc/
    volumes:
      - "./btc/btc/matchengine/config.json:/btc/matchengine/config.json"
      - "./btc/btc/accesshttp/config.json:/btc/accesshttp/config.json"
      - "./btc/btc/marketprice/config.json:/btc/marketprice/config.json"
      - "./btc/btc/accessws/config.json:/btc/accessws/config.json"
      - "./btc/btc/alertcenter/config.json:/btc/alertcenter/config.json"
      - "./btc/btc/readhistory/config.json:/btc/readhistory/config.json"
      - "./btc/tmp:/tmp/"
    ports:
      - "127.0.0.1:17416:7416"
      - "127.0.0.1:17316:7316"
      - "127.0.0.1:17317:7317"
      - "127.0.0.1:17424:7424"
      - "127.0.0.1:14444:4444"
      - "127.0.0.1:18080:8080"
      - "127.0.0.1:18081:8081"
      - "127.0.0.1:18901:8091"
    extra_hosts:
      - "dockerhost:172.21.0.1"
    depends_on:
      - mysql
      - mq
      - redis_sentinel
      - redis_slave
      - redis_master
    links:
      - mysql:db
      - mq:mq
      - redis_sentinel
      - redis_slave
      - redis_master
    networks:
      - trade
      - exchange 
    
  redis_master:
    container_name: btc-redis-master
    image: redis:4.0.2-alpine
    ports:
      - "127.0.0.1:16379:6379"
    networks:
      - trade


  redis_slave:
    container_name: btc-redis-slave
    image: redis:4.0.2-alpine
    ports:
      - "127.0.0.1:16380:6379"
    networks:
      - trade


  redis_sentinel:
    container_name: btc-redis-sentinel
    build: redis
    image: redis-sentinel
    environment:
      - MASTER_NAME=mymaster
      - QUORUM=1
      - MASTER=redis_master
      - SLAVES=redis_slave
    depends_on:
      - redis_master
    ports:
      - "127.0.0.1:26379:26379"
    networks:
      - trade


  mysql:
    container_name: btc-mysql
    build: ./db/
    ports:
      - "127.0.0.1:13306:3306"
    networks:
      - trade


  zookeeper:
    container_name: btc-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "127.0.0.1:12181:2181"
    networks:
      - trade


  mq:
    container_name: btc-kafka
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "127.0.0.1:19092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: mq
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - trade 

  nginx:
    image: nginx
    volumes:
      - "./nginx/sites-enabled/socket.conf:/etc/nginx/conf.d/socket.conf"
      - "./btc/tmp:/sockets"
    ports:
      - "8008:8008"

networks:
  trade:
    driver: bridge
  
  exchange:
    external:
      name: laradock_backend


